### PR TITLE
pull request for new UI

### PR DESCRIPTION
**Pull request by bertonbeil**
Hope this is correct pull request, if not please fix me

### CODE REVIEW

**Comment by christopherreay** [comment]
looks good. I'll have a look to resolve it in the morning x thanks

**Comment by bertonbeil** [comment]
good night, thank you too

2017-02-20 22:48 GMT+02:00 Christopher <notifications@github.com>:

**Comment by christopherreay** [comment]
OK. Ive merged the pull request. Its looking pretty good. The conflicts were all pretty obvious and simple.

There are two clear issues that I can see. One I can fix, but the other I would like you to fix.

If you can see on the production, there is an animation which shows when the calculation is waiting for the server, and a different animation when the calculation is rendering the SVG representation. This is managed very easily by a css class which is attached to the elements which animate. 

Could you find out where that is, and put the css class back?

This is a good thing for you to see in the code.

**Comment by christopherreay** [comment]
Im making the toggleFeatures into an SVGHUD plugin, which makes sense, and means they will be in the right place. Amazingly enough.

I used css to fix it, but this is the right solution

**Pull request merged**
